
version: "3.12"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 240111
    ports:
      - 5432:5432

  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: my_first_django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
